project: BGE Community Solar Pilot Program
project_id: 0081565

metadata:
  path: data/sample_communiuty_solar_data_2025_03_04.xlsx
  sheet: Community Solar Data
  values:
    report_run_date: B3
    period_start_date: B4
    period_end_date: B5
    account_id: E3
    account_name: E4
    electric_choice_id: E5
    bge_csegs_pilot_project_id: E6
    notes: I3
    some_other_field: null

energy_data:
  path: data/sample_communiuty_solar_data_2025_03_04.xlsx
  sheet: Community Solar Data
  header_row: 6
  column_mapping:
    Subscriber Choice ID: subscriber_choice_id
    Multiple CSEG Allocations: multiple_cseg_allocations
    Allocation Percentage: allocation_percentage
    Actual kWh Allocated: actual_kwh_allocated
    Initial Bank Balance kWh: initial_balance_kwh
    kWh Allocated from All Subscriptions: kwh_allocated_from_all_subscriptions
    Subscriber Billed Usage: subscriber_billed_usage
    Adjustment kWh: adjustment_kwh
    Final Bank Balance kWh: final_balance_kwh
    Community Solar Adjustment: community_solar_adjustment
    TOU Usage On Peak kWh: tou_usage_on_peak_kwh
    TOU Usage Intermediate Peak kWh: tou_usage_intermediate_peak_kwh
    TOU Usage Off Peak kWh: tou_usage_off_peak_kwh